//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2018 Retargetable Decompiler <info@retdec.com>
//

#include <signal.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/time.h>
#include <unistd.h>

// ----------------- Float Types Definitions ------------------

typedef float float32_t;
typedef double float64_t;

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

struct timeval {
    int32_t e0;
    int32_t e1;
};

// ------------------- Function Prototypes --------------------

int32_t function_400a00(void);
int32_t function_400b38(int32_t * a1, int32_t a2);
int32_t function_400c30(void);
int32_t function_401020(int32_t a1);
int32_t function_401070(float32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t function_40111c(void);

// --------------------- Global Variables ---------------------

int32_t g1 = 0; // a2
int32_t g2 = 0; // a3
float64_t g3 = 0.0; // fd0
float64_t g4 = 0.0; // fd12
float64_t g5 = 0.0; // fd14
int32_t g6 = 0; // fp
int32_t g7 = 0;
struct _IO_FILE * g8 = NULL;
struct _IO_FILE * g9 = NULL;
int32_t g10 = 0; // ra

// ------------------------ Functions -------------------------

// Address range: 0x400a00 - 0x400a88
int32_t function_400a00(void) {
    // 0x400a00
    setvbuf(g9, NULL, 2, 0);
    setvbuf(g8, NULL, 2, 0);
    signal(SIGALARM, 0x4009e0);
    return alarm(30);
}

// Address range: 0x400ac0 - 0x400b38
int main(int argc, char ** argv) {
    // 0x400ac0
    int32_t v1; // bp-40
    g6 = &v1;
    function_400a00();
    int32_t tp = 0; // bp-16
    gettimeofday((struct timeval *)&tp, NULL);
    int32_t seed;
    srand(seed);
    function_400c30();
    // branch -> 0x400ad8
    while (function_40111c() == 1) {
        // 0x400ad8
        gettimeofday((struct timeval *)&tp, NULL);
        srand(seed);
        function_400c30();
        // continue -> 0x400ad8
    }
    // 0x400b1c
    return 0;
}

// Address range: 0x400b38 - 0x400c30
int32_t function_400b38(int32_t * a1, int32_t a2) {
    int32_t v1 = g10; // 0x400b3c
    int32_t v2 = g6; // 0x400b40
    int32_t v3; // bp-40
    g6 = &v3;
    int32_t v4 = (int32_t)a1; // 0x400b48
    g1 = a2;
    memset((int32_t *)v4, 0, a2);
    uint32_t v5 = a2 - 1; // 0x400be8
    int32_t result; // 0x400c10
    if (v5 == 0) {
        // 0x400c04
        result = v5 + v4;
        *(char *)result = 0;
        g10 = v1;
        g6 = v2;
        return result;
    }
    int32_t v6 = 0;
    // branch -> 0x400b80
    while (true) {
        char buf = 0; // bp-12
        g1 = 1;
        if (read(0, (int32_t *)&buf, 1) <= -1) {
            // 0x400ba4
            exit(0);
            // UNREACHABLE
        }
        if (buf == 10) {
            // 0x400c04
            result = v5 + v4;
            *(char *)result = 0;
            g10 = v1;
            g6 = v2;
            return result;
        }
        // 0x400bc0
        *(char *)(v6 + v4) = buf;
        uint32_t v7 = v6 + 1; // 0x400bd8
        if (v7 >= v5) {
            // break -> 0x400c04
            break;
        }
        v6 = v7;
        // continue -> 0x400b80
    }
    // 0x400c04
    result = v5 + v4;
    *(char *)result = 0;
    g10 = v1;
    g6 = v2;
    return result;
}

// Address range: 0x400c30 - 0x401020
int32_t function_400c30(void) {
    int32_t v1 = g6; // 0x400c38
    int32_t v2; // bp-216
    g6 = &v2;
    int32_t v3 = 8; // bp-184
    char * v4 = (char *)0x6557; // bp-156
    int32_t v5 = 0; // bp-100
    memcpy(&v5, &g7, 36);
    int32_t tp = 0; // bp-64
    gettimeofday((struct timeval *)&tp, NULL);
    int32_t v6 = &v3; // 0x400dd8
    int32_t v7 = function_401020(8); // 0x400dc8
    int32_t * v8 = (int32_t *)(4 * v3 + v6 + 84); // 0x400de0
    int32_t * v9 = (int32_t *)(4 * v7 + v6 + 84); // 0x400df8
    *v8 = *v9;
    *v9 = *v8;
    int32_t v10 = v3 - 1; // 0x400e2c
    v3 = v10;
    // branch -> 0x400dc0
    while (v10 > 0) {
        // 0x400dc0
        v7 = function_401020(v10);
        v8 = (int32_t *)(4 * v3 + v6 + 84);
        v9 = (int32_t *)(4 * v7 + v6 + 84);
        *v8 = *v9;
        *v9 = *v8;
        v10 = v3 - 1;
        v3 = v10;
        // continue -> 0x400dc0
    }
    int32_t v11 = (int32_t)&v4; // 0x400e80
    int32_t str = 0; // bp-168
    int32_t v12 = 0;
    // branch -> 0x400e4c
    while (true) {
        int32_t * v13 = (int32_t *)(4 * v12 + v6 + 84); // 0x400e70
        // branch -> 0x400e4c
        while (true) {
            // 0x400e4c
            function_400b38(&str, 9);
            if (strcmp((char *)&str, (char *)(6 * *v13 + v11)) != 0) {
                // 0x400ea4
                puts("no!!! guess it!!!!!!");
                // branch -> 0x400eb4
            }
            // 0x400eb4
            if (strcmp((char *)&str, (char *)(6 * *v13 + v11)) == 0) {
                // break -> 0x400ef8
                break;
            }
            // continue -> 0x400e4c
        }
        int32_t v14 = v12 + 1; // 0x400efc
        if (v14 >= 9) {
            // break -> 0x400f14
            break;
        }
        v12 = v14;
        // continue -> 0x400e4c
    }
    int32_t tp2 = 0; // bp-56
    gettimeofday((struct timeval *)&tp2, NULL);
    int32_t v15;
    int32_t v16;
    function_401070((float32_t)tp, v16, tp2, v15);
    function_401070((float32_t)tp, v16, tp2, v15);
    printf((char *)(int32_t)"\n\n%.0lf sec, %.0lf usec\n", g4, g5);
    function_401070((float32_t)tp, v16, tp2, v15);
    int32_t result = 0;
    if (-1.3923507385478714e-241 * g3 < 1.0434666440167127e-320) {
        // 0x400fdc
        puts("... go!");
        int32_t v17 = 0; // bp-48
        result = function_400b38(&v17, 1024);
        // branch -> 0x401000
    }
    // 0x401000
    g6 = v1;
    return result;
}

// Address range: 0x401020 - 0x401070
int32_t function_401020(int32_t a1) {
    // 0x401020
    return rand() % a1;
}

// Address range: 0x401070 - 0x40111c
int32_t function_401070(float32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    // 0x401070
    g2 = a4;
    g1 = a3;
    g3 = 1.065277785087841e-314 * (float64_t)(float32_t)g1 + (float64_t)(float32_t)g2 - (1.065277785087841e-314 * (float64_t)(float32_t)(int32_t)a1 + (float64_t)(float32_t)a2);
    return g2;
}

// Address range: 0x40111c - 0x401190
int32_t function_40111c(void) {
    int32_t v1 = 0; // bp-16
    scanf(" %c%*c", &v1, (int32_t *)g1, (char *)g2);
    int32_t result;
    if (v1 != 121) {
        // 0x401158
        result = v1 == 89;
        // branch -> 0x401178
    } else {
        result = 1;
    }
    // 0x401178
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// unsigned int alarm(unsigned int seconds);
// void exit(int status);
// int gettimeofday(struct timeval * restrict tv, __timezone_ptr_t tz);
// void * memcpy(void * restrict dest, const void * restrict src, size_t n);
// void * memset(void * s, int c, size_t n);
// int printf(const char * restrict format, ...);
// int puts(const char * s);
// int rand(void);
// ssize_t read(int fd, void * buf, size_t nbytes);
// int scanf(const char * restrict format, ...);
// int setvbuf(FILE * restrict stream, char * restrict buf, int modes, size_t n);
// __sighandler_t signal(int sig, __sighandler_t handler);
// void srand(unsigned int seed);
// int strcmp(const char * s1, const char * s2);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.6.3)
// Detected functions: 7
// Decompilation date: 2018-09-03 15:59:24
